### ISSUE TITLE
Error when deploying

### ISSUE THREAD

**Issue by summer18** [Pixel2HTML/shopify-skeleton#2]
Hi, i'm getting this error when i run npm run deploy
```
[01:58:20] { HTTPError
    at stream.catch.then.data (C:\Users\maku\WebProjects\shopify\pixel2html\node_modules\got\index.js:123:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Response code 404 (Not Found)',
  host: undefined,
  hostname: 'bizhelper.myshopify.com',
  method: 'PUT',
  path: '/admin/themes/6570967077/assets.json',
  statusCode: 404,
  statusMessage: 'Not Found' }
```

**Comment by shelldandy** [comment]
You need to define you `.env` file and make sure it's properly filled

**Comment by summer18** [comment]
i did put all the credentials, even change to another store, but it still can't connect to shopify,
hurmm kinda strange..

**Comment by shelldandy** [comment]
@summer18 make sure your credentials have read and write access to the theme assets

**Comment by shelldandy** [comment]
hey there @summer18 i just read your path seems like you're on a windows machine, i had that issue reported and I reported it again to the actual gulp package that has the trouble here:

https://github.com/tmslnz/gulp-shopify-theme/issues/4

I even added a dirty hotfix to it, I'm planning on eventually forking that package to give it more support and the features I need, but in the meantime i guess you can do that hotfix

**Comment by summer18** [comment]
Thanks, @mike3run, I did the hotfix and it was ok, except the gulp still unable to resolve the path on subdirectory under templates -> src/theme/templates/customer, probably due to my windows.

**File templates/customers%5Caddresses.liquid added**

Should it be like this right?
`File templates/customers/addresses.liquid added`

One more thing, I can see that all the files being uploaded, however, 
the full-deploy task left hanging there after the task finished, is it like that?

```    
[00:57:39] File templates/404.liquid added                 
[01:13:50] File templates/article.liquid added             
[01:13:50] File templates/blog.liquid added                
[01:13:50] File templates/cart.liquid added                
[01:13:50] File templates/collection.liquid added          
[01:13:50] File templates/gift_card.liquid added           
[01:13:50] File templates/index.liquid added               
[01:13:50] File templates/list-collections.liquid added    
[01:13:50] File templates/page.contact.liquid added        
[01:13:50] File templates/page.liquid added                
[01:13:50] File templates/password.liquid added            
[01:13:50] File templates/product.liquid added             
[01:13:50] File templates/search.liquid added              
[01:13:50] File locales/es.json added
[01:13:51] File sections/featured-collection.liquid added
[01:13:53] Likely a Liquid syntax error
[01:13:53] { HTTPError
    at stream.catch.then.data (C:\Users\maku\WebProjects\shopify\test-demo\node_modules\got\index.js:123:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Response code 422 (Unprocessable Entity)',
  host: undefined,
  hostname: 'my-demotest.myshopify.com',
  method: 'PUT',
  path: '/admin/themes/6681100319/assets.json',
  statusCode: 422,
  statusMessage: 'Unprocessable Entity' }

**[01:13:53] File templates/customers%5Caccount.liquid added**
[01:13:54] Likely a Liquid syntax error
[01:13:54] { HTTPError
    at stream.catch.then.data (C:\Users\maku\WebProjects\shopify\test-demo\node_modules\got\index.js:123:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Response code 422 (Unprocessable Entity)',
  host: undefined,
  hostname: 'my-demotest.myshopify.com',
  method: 'PUT',
  path: '/admin/themes/6681100319/assets.json',
  statusCode: 422,
  statusMessage: 'Unprocessable Entity' }

**[01:13:54] File templates/customers%5Cactivate_account.liquid added**
[01:13:55] Likely a Liquid syntax error
[01:13:55] { HTTPError
    at stream.catch.then.data (C:\Users\maku\WebProjects\shopify\test-demo\node_modules\got\index.js:123:13)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  message: 'Response code 422 (Unprocessable Entity)',
  host: undefined,
  hostname: 'my-demotest.myshopify.com',
  method: 'PUT',
  path: '/admin/themes/6681100319/assets.json',
  statusCode: 422,
  statusMessage: 'Unprocessable Entity' }

**[01:13:55] File templates/customers%5Caddresses.liquid added**
Finished 'full-deploy' after 46 s
Terminate batch job (Y/N)? y
```

**Comment by shelldandy** [comment]
> One more thing, I can see that all the files being uploaded, however,
the full-deploy task left hanging there after the task finished, is it like that?

Sadly yes, that's another reason I want to fork that plugin to be able to provide a callback. But at least works manually

You can see I added another issue about it on the plugin github right here

https://github.com/tmslnz/gulp-shopify-theme/issues/3

**Comment by jb-angus** [comment]
@mike3run This issue still seems to exist for Windows users. I have been able to get around it by manually changing gulp-shopify-theme with your hack

`basepath = basepath[0].replace('\\', '/');`

It looks like the latest gulp-shopify-theme version has a fix in place, are you able to update your fork with the latest?

Great project BTW :)
