### ISSUE TITLE
Missing or invalid options

### ISSUE THREAD

**Issue by pjatx** [Pixel2HTML/shopify-skeleton#5]
Starting today, I'm not able to deploy any new code due to a config / auth issue. 

Steps to Reproduce: 
Run `gulp serve` or `gulp deploy`

Expected: 
* Theme files upload and tasks run as expected

Actual:
* Receiving the following error:

```
[18:21:27] Finished 'watch' after 33 ms
[18:21:27] 'theme:init' errored after 33 ms
[18:21:27] Error: Missing or invalid options
    at new Shopify (/Users/philipjohnson/projects/store-test/node_modules/shopify-api-node/index.js:36:11)
    at ShopifyTheme.makeConfig (/Users/philipjohnson/projects/store-test/node_modules/gulp-shopify-theme/index.js:97:24)
    at ShopifyTheme.init (/Users/philipjohnson/projects/store-test/node_modules/gulp-shopify-theme/index.js:82:14)
    at gulp.task.done (/Users/philipjohnson/projects/store-test/gulp/tasks/deploy.js:24:27)
    at taskWrapper (/Users/philipjohnson/projects/store-test/node_modules/undertaker/lib/set-task.js:13:15)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at asyncRunner (/Users/philipjohnson/projects/store-test/node_modules/async-done/index.js:39:18)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickDomainCallback (internal/process/next_tick.js:218:9)
[18:21:27] 'serve' errored after 34 ms
[18:21:27] 'default' errored after 2.7 s
[18:21:27] The following tasks did not complete: browser-sync, theme:watch
[18:21:27] Did you forget to signal async completion?
```

I hadn't changed any configs or env variables, so thought this was strange. Dug into it, finally created a brand new test store and fresh theme and was able to reproduce it. 

Maybe issue with Shopfy's API, but checked the status page and everything looks normal.

**Comment by shelldandy** [comment]
remember to give your api credentials read write access to the theme files

**Comment by pjatx** [comment]
It does in both cases. With my existing and new store I'm experiencing this issue (just started today).

**Comment by shelldandy** [comment]
<img width="960" alt="screen shot 2017-12-10 at 7 42 35 pm" src="https://user-images.githubusercontent.com/7088511/33812353-73df149e-dde2-11e7-9e56-b0e90e952b19.png">

**Comment by shelldandy** [comment]
Just checked now and its working fine, but i can see the gulp shopify plugin got a facelift yesterday so ask the dev away: 

https://github.com/tmslnz/gulp-shopify-theme

**Comment by shelldandy** [comment]
You could also point your package.json to the fork i did of that plugin like 5 days ago:

`"gulp-shopify-theme": "mike3run/gulp-shopify-theme"`

**Comment by pjatx** [comment]
Ah - the update of the plugin is what broke it. Went back to 1.0.14 and it works again.

**Comment by shelldandy** [comment]
@pjatx I'm rolling out the beta release you can try it out by doing

`npm install -g generator-pixel2html-shopify@beta`
