### ISSUE TITLE
Error: Received a non-Vinyl object in `dest()`

### ISSUE THREAD

**Issue by antekera** [Pixel2HTML/shopify-skeleton#7]
When make npm run code i get this error:

 Error: Received a non-Vinyl object in `dest()`

**Comment by shelldandy** [comment]
I need more details man

**Comment by antekera** [comment]
This is the complete error:

`[13:51:12] 'vendor:scripts' errored after 942 ms
[13:51:12] Error: Received a non-Vinyl object in `dest()`
    at DestroyableTransform.normalize [as _transform] (/Users/mike/Work/patagonia/shopify/node_modules/vinyl-fs/lib/dest/prepare.js:16:17)
    at DestroyableTransform.Transform._read (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_transform.js:182:10)
    at DestroyableTransform.Transform._write (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_transform.js:170:83)
    at doWrite (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at DestroyableTransform.Writable.write (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:322:11)
    at Pumpify.Duplexify._write (/Users/mike/Work/patagonia/shopify/node_modules/duplexify/index.js:212:22)
    at doWrite (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:406:64)
    at writeOrBuffer (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:395:5)
    at Pumpify.Writable.write (/Users/mike/Work/patagonia/shopify/node_modules/readable-stream/lib/_stream_writable.js:322:11)`

i also get this error on npm install:

`npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN prefer global node-gyp@3.6.2 should be installed with -g`

**Comment by shelldandy** [comment]
What version of this package you are using?

Seems like an issue with a library you're importing.

Need even more details...

**Comment by shelldandy** [comment]
It also seems like you're using a previous version that used browserify, we're using webpack now

**Comment by shelldandy** [comment]
Make sure you're on v.3.0.4 please

**Comment by antekera** [comment]
I´m using ` yo @pixel2html/shop-generator` but i think is not the same version as in master branch.

**Comment by shelldandy** [comment]
there you go. just gotta update and run again, npm and master branch are in sync
