### ISSUE TITLE
babel-prest-env error when running webpack scripts

### ISSUE THREAD

**Issue by pjatx** [Pixel2HTML/shopify-skeleton#9]
Me again : ) 

Just picked up a new project and trying to run `npm run webpack` and getting the following.

Have tried installing the package, updating NPM, and a few other things but can't get it to go away.  

```
ERROR in ./src/scripts/index.js
Module build failed: Error: Cannot find module 'babel-preset-env' from '/Users/philipjohnson/projects'
    at Function.module.exports [as sync] (/Users/philipjohnson/projects/vue-shopify/node_modules/resolve/lib/sync.js:40:15)
    at resolveStandardizedName (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/files/plugins.js:78:29)
    at resolvePreset (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/files/plugins.js:31:10)
    at loadPreset (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/files/plugins.js:50:18)
    at createDescriptor (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:135:21)
    at /Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:101:12
    at Array.map (<anonymous>)
    at createDescriptors (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:100:27)
    at createPresetDescriptors (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:92:10)
    at /Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:64:19
    at presets (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-descriptors.js:54:25)
    at mergeChainOpts (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-chain.js:294:68)
    at /Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-chain.js:247:7
    at buildRootChain (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/config-chain.js:83:20)
    at loadConfig (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/config/index.js:50:53)
    at transformSync (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/transform-sync.js:13:36)
    at Object.transform (/Users/philipjohnson/projects/vue-shopify/node_modules/@babel/core/lib/transform.js:20:65)
    at transpile (/Users/philipjohnson/projects/vue-shopify/node_modules/babel-loader/lib/index.js:55:20)
    at /Users/philipjohnson/projects/vue-shopify/node_modules/babel-loader/lib/fs-cache.js:116:18
    at ReadFileContext.callback (/Users/philipjohnson/projects/vue-shopify/node_modules/babel-loader/lib/fs-cache.js:36:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)
```

**Comment by shelldandy** [comment]
Will give a look next week thanks for the report

**Comment by antekera** [comment]
Try adding `"babel": {
    "presets": ["module:@pixel2html/babel-preset"]
  }` in package.json

**Comment by pjatx** [comment]
@antekera just looping back to this for another project. Thanks for the suggestion, but unfortunately the same outcome

**Comment by shelldandy** [comment]
Will move this issue to our monorepo to deal with it
